"""
Django settings for djangoProject3 project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import django.apps

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u4a!$)#xd&=5g&dubhwvplpj@74q5rfg4lhklfy5hz4qdod6%v'

# SECURITY WARNING: don't run with debug turned on in production!
# 调试模式 在开发中打开方便查看问题  项目上线后关闭
DEBUG = True
#允许以什么样的方式访问我们的地址
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'book.apps.BookConfig' #注册bookapp
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoProject3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #告知系统 模板发文件的存放位置
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
#关系型数据库
#过度 了解
DATABASES = {
    'default': {

        # 改为mysql
        'ENGINE': 'django.db.backends.mysql',
        # 'ENGINE': 'django.db.backends.sqlite3',
        "HOST":"127.0.0.1",#主机
        "PORT":'3306',
        "USER":"root",
        "PASSWORD":"fxxh521",
        'NAME': "book",#创建的表的名字
        # 'NAME': BASE_DIR / 'db.sqlite3',
    #     此时会报错 did you install mysqlclient? 到中断中 pip install mysqlclient
        #注意使用最新的mysql会报错，原因在于django暂不支持新的加密方式caching_sha2_password，解决方案为：


            # 1.登录mysql，连接用户为root。
            # > mysql -u root -p
            #
            # 2.执行命令查看加密方式
            # > use mysql;
            # > select user,plugin from user where user='root';
            #
            # 3.执行命令修改加密方式
            # > alter user 'root'@'localhost' identified with mysql_native_password by 'yourpassword'
            #
            # 4.属性权限使配置生效
            # > flush privileges
        # 配置完成后重新进行表的迁移工作
        # 1 python manage.py makemigrations
        # No changes detected
        # 2 python manage.py migrate
        }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans' #'en-us'
#默认为英文，改为中文

TIME_ZONE = 'Asia/Shanghai'#'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# 访问时的路由为：http://127.0.0.1:8000/static/aboat.png
#其中aboat.png为图片名称，与static url配置的参数一致
STATIC_URL = '/static/'
#告诉系统图片放在哪里
STATICFILES_DIRS=[


    os.path.join(BASE_DIR,"static")
]
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
