# Generated by Django 3.2.9 on 2021-12-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20211206_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='is_deleate',
            new_name='is_delete',
        ),
    ]
